### ISSUE TITLE
Some IDs got mangled

### ISSUE THREAD

**Issue by matentzn** [insect-morphology/aism#40]
Working with @JCGiron on something else, I noticed that quite a few ids in AISM are mangled up:

http://purl.obolibrary.org/obo/AISM/AISM_0002064
instead of http://purl.obolibrary.org/obo/AISM_0002064

this should be fixed asap, if you don't want to break some OBO assumptions :)

**Comment by JCGiron** [comment]
So we noticed this before. It was caused by one of our contributors having their Protégé configured differently to auto-generate IRI's. We have fixed it in the aism-edit.owl file, but those changes are not yet in the latest version. Technically, the next release will incorporate this change.

**Comment by JCGiron** [comment]
New release has been updated to solve this issue.
