### ISSUE TITLE
What is the rationale for having multiple EquivalentClass axioms (AKA logical definitions) on a single term?

### ISSUE THREAD

**Issue by dosumis** [insect-morphology/aism#43]
Example:
![image](https://user-images.githubusercontent.com/112839/126139969-6690ff32-8eb7-41ed-81e2-4a60d054ed13.png)

**Comment by JCGiron** [comment]
It might have been a testing situation for reasoning purposes. @sergeitarasov might have a better answer?

**Comment by JCGiron** [comment]
The issue has been corrected in the latest release:
![image](https://user-images.githubusercontent.com/37313282/127783388-aa325b65-1373-4f00-a716-5aebad5c866b.png)
We have now only one necessary and sufficien EquivalentClass axiom for the subclass cercus.

**Comment by dosumis** [comment]
Sounds necessary but not sufficient. Don't Cerci stick out? (presumably the point of 'cuticular protrusion'.)

**Comment by JCGiron** [comment]
True. I'll fix this for the next release. Thanks for checking!

**Comment by sergeitarasov** [comment]
The rationale for having multiple classes was to cover all variation across insects that matches the definition of cercus, I think those classes can be combined into one using 'OR' operator but this would reduce readability. 
I wonder if the new definition of cercus returns the desired result in reasoning?

**Comment by dosumis** [comment]
> The rationale for having multiple classes was to cover all variation across insects that matches the definition of cercus

The result of this will be the inference that all cerci (and anything that matches one of the equivalentClass definitions) have all the properties of the different variants.  I suspect you don't want this inference. 

> I think those classes can be combined into one using 'OR' operator but this would reduce readability.

This is certainly safer, but will suffer from unscalable reasoning.

Other options 
   - make names subclasses for variants and add equivalent Class definitions to these.
   - Use GCIs to achieve the same without naming subclasses:
          {some class expression} subClassOf cercus
          {some other class expression} subClassOf cercus

> I wonder if the new definition of cercus returns the desired result in reasoning?

Did you work back from curated individuals to write the equivalent Class defs?  I think this is a useful exercise in trying to understand how users will work with AISM to describe morphological characters.  That should then lead to a discussion of how to reconcile use in annotation with ontology axiomatisation.  Some pattern/template based system might work well across curation of individuals and ontology classes to keep them aligned.  Some improved axiomatisation of the ontology might help (property chains, property characteristics)

My main other worry here is the disconnect between logical definitions and textual definitions.  Any editor should be able to see the connection and understand the axiomatisation.   The new definition is closer to the text def in ontology and paper:

'The paired appendage of the postabdomen located between the epiproct and the paraproct'

I assume the use of appendage here is different from that in the ontology and so cuticular protrusion is preferred?  If so it is worth at least having a comment to explain the difference in language.  IIRC, you do a good job of recording A-P ordering in the ontology, so you may be able to achieve a useful def based on that.

But perhaps all this is too complex.  From the paper, it looks like all you need to distinguish cercus from cornicle is location.

**Comment by sergeitarasov** [comment]
> The result of this will be the inference that all cerci (and anything that matches one of the equivalentClass definitions) have all the properties of the different variants. I suspect you don't want this inference.

Thanks for noticing it! My mistake -- I thought that listing Eq. classes is the same as joining them with  'OR'.

> My main other worry here is the disconnect between logical definitions and textual definitions.

The textual and logical definitions might be different throughout the AISM (at least the version used for the reasoning). We should revise it. In the case of 'cercus', the correct definition (we agreed upon the last discussion) was the logical one. In fact, 'cercus' is a mixture of 'unrelated' structures that implies a mixture of 'unrelated' logical defs.

> 'Other options'

Agreed. these approaches is the way to go

**Comment by sergeitarasov** [comment]
I've tried to fix the reasoning of cercus through intermediate classes (cercus type 1, cercus type 2 and cercus type 3). The new version is pushed to https://github.com/sergeitarasov/AISM_Reasoning. Please have a look @dosumis and @JCGiron.

As previosuly two files are relevant data/aism_instances.owl and  results/aism_instances-Konclude.owl
