### ISSUE TITLE
Meeting minutes 19.07.2021

### ISSUE THREAD

**Issue by matentzn** [insect-morphology/aism#45]
- [x] Never add multiple equivalents to axioms on a single class. (example: `cersus` has 3)
- https://github.com/insect-morphology/aism/pull/44 introduces a simple Google Sheets pipeline for generating examples from a ROBOT template

**Comment by JCGiron** [comment]
I corrected the issue with cercus and added a few unique equivalent to axioms throughout the AISM. I'll pull the spreadsheet workflow as I think reasoning using ROBOT might be more straightforward than what we currently have.

**Comment by JCGiron** [comment]
I corrected the issue with cercus and added a few unique equivalent to axioms throughout the AISM. I'll pull the spreadsheet workflow as I think reasoning using ROBOT might be more straightforward than what we currently have.
For now the changes are only in the edit version, not in the released version.
