### ISSUE TITLE
region of cuticle should be part_of 'region of insect integument' not subClassOf

### ISSUE THREAD

**Issue by dosumis** [insect-morphology/aism#51]
![image](https://user-images.githubusercontent.com/112839/134947829-8e580b67-ffc6-4efd-a447-dad8d312c157.png)

"insect region of integument": "A region of cuticle and its underlying epidermis."
=> subClassOf is not correct here - it's a part of a region of integument.

**Comment by JCGiron** [comment]
Changed to 'part of' [Nov 19 2021]

![image](https://user-images.githubusercontent.com/37313282/142670755-b097d67a-7c65-48ba-8310-b3549c334117.png)
