### ISSUE TITLE
Make  Google sheet with template for term addition.

### ISSUE THREAD

**Issue by dosumis** [insect-morphology/aism#52]
Example from notes for paper:

![image](https://user-images.githubusercontent.com/112839/134948989-fdf289cf-28cb-4a1c-873f-a618826fd879.png)

region of cuticle type | location | bilaterally paired | adjacent_to | posterior to | anterior to
cuticular protrusion |

**Comment by JCGiron** [comment]
The template is available now at https://github.com/insect-morphology/aism/blob/master/AISM_template_examples.tsv.

We added general instructions to the manual: https://github.com/insect-morphology/Manual/blob/main/Sections/Using-templates.md, which are linked at the bottom of the main README of the manual.
