### ISSUE TITLE
Add obo-foundry uniquename to distinguish terms that sound like they refer to whole body or integument regions.

### ISSUE THREAD

**Issue by dosumis** [insect-morphology/aism#53]
All (?) subclasses of 'region of cuticle' in AISM should have a synonym & an obo-foundry uniquename = 'cuticle of X', e.g. antenna -> 'cuticle of antenna'.  This is needed to avoid confusion of reference in a broader context - if these terms are integrated with other ontologies, e.g. DAO where 'antenna' refers to the whole structure of the antenna including epithlium, sensory organ cells, muscles, trachea etc.  This process can be automated using Robot.

**Comment by JCGiron** [comment]
Corrected in latest release (v2021-12-13).
