### ISSUE TITLE
clarify the scope of this ontology

### ISSUE THREAD

**Issue by cmungall** [insect-morphology/aism#57]
skeleto-muscular has a particular meaning in the context of other anatomy ontologies in OBO, AISM seems to include antennae, legs, appendage, cuticles, thoraxes, etc. To be sure these have skeleto-muscular parts but these also involve other systems

**Comment by JCGiron** [comment]
See this issue: https://github.com/insect-morphology/aism/issues/53

Yes, we need to be more explicit, especially with our labels, since we are referring specifically to the cuticular and muscular system and not including nevous, circulatory and other systems. 
Will work on these adjustments soon.

**Comment by cmungall** [comment]
great - and it looks like this needs to propagate down to subclassing ontologies like lepao and colao

**Comment by JCGiron** [comment]
Corrected in latest release (v2021-12-13).
Corrections soon to be applied to AISM-derived ontologies.
