### ISSUE TITLE
Add IAO:0000700 annotations

### ISSUE THREAD

**Issue by matentzn** [insect-morphology/aism#67]
Dear AISM team, we are trying to drive proper cross OBO integration forward which will include a flurry of issues to be dealt with.

Would you be able to help us with this? First step:

[Adding IAO:0000700 annotations to your ontology](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2149).

**Comment by JCGiron** [comment]
Hi Nico!
Yes, I'll try to get this done later today ot tomorrow.

**Comment by JCGiron** [comment]
@matentzn, @cthoyt  
Would this be the appropriate way to annotate [has ontology root term](http://purl.obolibrary.org/obo/IAO_0000700)?

![image](https://user-images.githubusercontent.com/37313282/194683769-8f0c1ea6-f2ea-4d73-b533-315fc07198b5.png)

**Comment by cthoyt** [comment]
Yes!

**Comment by JCGiron** [comment]
All right, new annotated files are in: https://github.com/insect-morphology/aism/releases/tag/v2022-10-08

**Comment by cthoyt** [comment]
@JCGiron Thanks for looking into this, but I'm wondering if the single term is enough - it's possible to annotate multiple. Here's a schematic diagram of the way the highest terms in AISM (as far as the hierarchy goes) connect up to other upper-level ontology terms. I guess the question for an ontology like this, what's the best way to go about picking roots? For sure it's possible to iterate over this until we find something that works best CC @matentzn 

![](https://camo.githubusercontent.com/429b44e7ba871e0ca362683e770c0ef552bb5406ae56fbf3cb1b0d01eb5ac9fe/68747470733a2f2f6374686f79742e636f6d2f636f622d726f6f742d616e616c797369732f726573756c74732f6169736d5f726573756c74732e737667)

**Comment by JCGiron** [comment]
Yes, I saw that and was thinking of the best way to approach it. I ended up choosing the term from the ontology that nests all/most of the terms we created. We could add higher level terms, perhaps 'chitin-based cuticle' (http://purl.obolibrary.org/obo/UBERON_0001001), but I'm not sure if a term from another ontology should/can be a root?
One of the issues with the AISM is that we have **a lot** of imports/hierarchies from UBERON (which is heavily vertebrate biased), for example, and lots of connections with BSPO that might "obscure" the things that we actually use.
If you have specific advice on terms that are candidates to be roots according to your analysis, we are happy to consider.

**Comment by cthoyt** [comment]
Based on the diagram, I'd suggest adding the following three high-level ones:
- CARO:0000000 (anatomical entity)
- UBERON:0001062 (anatomical entity)
- BFO:0000019 (quality)

It occurs to me that there's a lot of unaligned duplicates like UBERON:0001062 (anatomical entity) as well... not sure what's going on here, but these will all get aligned to COB anyway

**Comment by JCGiron** [comment]
Thank you for the suggestions.
I will add those next week when I come back home.

**Comment by matentzn** [comment]
I would suggest PATO:quality and UBERON:anatomicalEntity. We will have Caro replaced by COB, and PATO qualities should not be under BFO qualities - this is just wrong.

**Comment by cthoyt** [comment]
Definitely go with Nico's suggestions over mine, he knows much more about this

**Comment by JCGiron** [comment]
Thank you @matentzn and @cthoyt!
I'll work on this when I'm back.

**Comment by JCGiron** [comment]
Finally got around to do this.
PATO:quality and UBERON:anatomicalEntity are now additional roots in AISM.

![image](https://user-images.githubusercontent.com/37313282/213771055-98b44c2f-6dae-4216-9f3c-11140f3659ed.png)

**Comment by matentzn** [comment]
Excellent!

**Comment by JCGiron** [comment]
Just FYI, the AISM-derived [COLAO](https://github.com/insect-morphology/colao) also has root terms added now.
