### ISSUE TITLE
GitHub quality control failure - docker pull failed with exit code 1

### ISSUE THREAD

**Issue by JCGiron** [insect-morphology/aism#88]
We ran a new release of the ontology and GitHub quality control failed.

![image](https://github.com/insect-morphology/aism/assets/37313282/136a7f55-6443-4836-af51-21e963babd5b)

How can I fix this?

@matentzn @anitacaron

**Comment by anitacaron** [comment]
@JCGiron Could you please try again? Maybe it was a down time period in docker hub that could not download the image. I tried now and I could download the image without issues.

**Comment by JCGiron** [comment]
It worked!
Thank you, @anitacaron!
